// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "CrewFlow",
//   description: "Maritime Crew Management Platform",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body style={{ margin: 0, padding: 0, background: "#fffbf5" }}>
//         <nav style={{
//           background: "#ffffff",
//           borderBottom: "2px solid #fde8cc",
//           padding: "0 36px",
//           height: 60,
//           display: "flex",
//           alignItems: "center",
//           justifyContent: "space-between",
//           position: "sticky",
//           top: 0,
//           zIndex: 100,
//           boxShadow: "0 2px 12px rgba(249,115,22,.07)"
//         }}>
//           <a href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
//             <div style={{
//               width: 34, height: 34, borderRadius: 9,
//               background: "linear-gradient(135deg,#f97316,#ea580c)",
//               display: "flex", alignItems: "center",
//               justifyContent: "center", fontSize: 18
//             }}>⚓</div>
//             <div>
//               <div style={{ fontSize: 10, fontWeight: 700, color: "#f97316", letterSpacing: 2 }}>CREWFLOW</div>
//               <div style={{ fontSize: 12, fontWeight: 700, color: "#1a1a1a", marginTop: -1 }}>Maritime CMS</div>
//             </div>
//           </a>

//           <div style={{ display: "flex", gap: 4 }}>
//             {[
//               { href: "/dashboard", label: "📊 Dashboard" },
//               { href: "/relief", label: "🔔 Relief" },
//               { href: "/pool", label: "👤 Seafarer Pool" },
//               { href: "/vacancies", label: "📋 Vacancies" },
//               { href: "/checklist", label: "✅ Checklist" },
//             ].map(link => (
//               <a key={link.href} href={link.href} style={{
//                 padding: "6px 14px",
//                 borderRadius: 8,
//                 fontSize: 12,
//                 fontWeight: 600,
//                 color: "#9a3412",
//                 textDecoration: "none",
//               }}>
//                 {link.label}
//               </a>
//             ))}
//           </div>

//           <div style={{
//             background: "#f0fdf4",
//             border: "1px solid #bbf7d0",
//             borderRadius: 20,
//             padding: "4px 14px",
//             fontSize: 11,
//             fontWeight: 600,
//             color: "#15803d"
//           }}>
//             ● Live
//           </div>
//         </nav>

//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CrewFlow",
  description: "Maritime Crew Management Platform",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin:0, padding:0, background:"#0d0e12" }}>
        {children}
      </body>
    </html>
  );
}